### ISSUE TITLE
crash NullPointerException: Tesselating block model

### ISSUE THREAD

**Issue by rahangar** [TheCBProject/CodeChickenLib#115]
I reported this crash to AE2.

They asked me to report it to CodeChickenLib.  Please help.

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3251

I'm using CodeChickenLib-1.12-3.1.3.313-universal

**Comment by covers1624** [comment]
No, this is AE's issue or another mod breaking it's model. CCL is in the stack yes, because I have mechanics for blocks to render without the horribly slow forge render engine. This code has existed since early 1.8 and I highly doubt it's he issue and would have been reported thousands of times as ccl is such a high traffic mod.

**Comment by fscan** [comment]
FYI, that's basically true for the drive model too.
