### ISSUE TITLE
your mod is terrible and you should feel terrible

### ISSUE THREAD

**Issue by DataCrusader** [TheCBProject/CodeChickenLib#135]

**Comment by covers1624** [comment]
Seriously, where do you get off? Let me guess, your probably 12 sitting in your mothers basement with a couple mates going "Yeah lets spam that issue tracker with random bullshit because we had one issue with CCL and don't wanna submit a proper issue report". Well it got you reported to git and blocked from this organization, all you have done is create work and waste my time that would otherwise be spent enjoying my holidays and break from modding. If that was your end goal, well done good sir, i applaud your intellect and rationale behind opening issues!

**Comment by gigabit101** [comment]
Why do people do crap like this its so childish...
