### ISSUE TITLE
Resource Leak in OBJLoader

### ISSUE THREAD

**Issue by ichttt** [TheCBProject/CodeChickenLib#145]
Hi, you have a resource leak because an IResource isn't closed here:
https://github.com/TheCBProject/CodeChickenLib/blob/c68dcf0208267a8c432dd3f7a58024d9a2fb48c4/src/main/java/codechicken/lib/render/OBJParser.java#L64

Just close your IResouce in a finally block or with try-with-resources, and you will be fine.
These leaks can be observed by forcing debug to be enabled for minecraft loggers using the log4j xml

**Comment by xerberus333** [comment]
Hey, was just wondering if there was any progress made with this. Many new versions have been uploaded to curseforge since this post, but I couldn't find a changelog.

I'm currently using [Ancient Warfare 2](https://minecraft.curseforge.com/projects/ancient-warfare-2/relations/dependencies), and wondering how much this could affect me.

**Comment by covers1624** [comment]
Completely forgot about this issue, https://github.com/TheCBProject/CodeChickenLib/commit/166374737fbe893b6433192b67f29bdc75e7775d. Currently getting back-end stuff ready for the next release, doing some infrastructure changes.
