### ISSUE TITLE
Register Help with IItemRenderer

### ISSUE THREAD

**Issue by ghost** [TheCBProject/CodeChickenLib#155]
I have problem with IItemRenderer,
when i register armor (item) / block or tileentity
i have problem with texture:
![error](https://user-images.githubusercontent.com/27679699/41428268-ce044d22-7009-11e8-8507-9993bb8b531b.png)

the function to register:
![code1](https://user-images.githubusercontent.com/27679699/41428284-dac7e5f0-7009-11e8-98ae-c56afe298a09.png)

the function use by IItemRenderer:
![code2](https://user-images.githubusercontent.com/27679699/41428302-ea4b54da-7009-11e8-9932-8ba75692d69b.png)

can you help me ?
thanks in advance.

**Comment by covers1624** [comment]
There really isn't much information here.. Why is your method named `renderOverlay`, it doesn't render anything, id call it `registerOverlayRenderer`, furthermore why is it red underlined, eclipse is telling you something.  
What happens to your item? Does its model not show? Does it show in the corner? Does it break the characters skin like that? I literally have no information. If you can provide a little more insight to what the actual problem is in your screenshot that'd be nice.

**Comment by ghost** [comment]
1) renderOverlay render IOverlayRender (Directly inspired of Overlay of Avaritia (the halo))
2) the red line is fixed
3) item not a problem but armor (texture when equiped (screenshot 1)) does not renderer and block too when overlay boolean is true and IOverlayRender is Assigned in ItemArmorMaster
4) no
5) similar to 3
6) yea is see and i uploaded all need in repo: [Help Git](https://github.com/TokyoSU/Mods/tree/master/help)

**Comment by covers1624** [comment]
I don't think this has anything to do with CCL, add some println calls in your IItemRenderer.renderItem method to see if its being called, other than that, i cant really help you much sorry, there is heaps of example code for IItemRenderer registration that you can use as reference.

**Comment by ghost** [comment]
EDIT: TransformType as Only for GUI: [OverlayRender](https://github.com/TokyoSU/Mods/blob/0175c56b48d442fab7204fa1662f980951b5b41c/help/OverlayRender.java#L42)
This is the OverlayRender, basically is Avaritia with custom add,
need to be type.HEAD ?

**Comment by covers1624** [comment]
This wasn't a CCL issue.
