### ISSUE TITLE
[1.12.2] CodeChickenLib Sending sync packet to player causes NetworkDispatcher exception

### ISSUE THREAD

**Issue by chaos234** [TheCBProject/CodeChickenLib#171]
Like the title states it is definitly related to this mod, that there is a direct DC/Time Out and there is nothing what can be done to solve this.

It doesn't matter which client I use to start the FTB Revelation pack but it can't be that a config sync causes this much trouble and this is not limited to me, it is also affecting other players which are trying to connect to the server.

Means that it doesn't depend on the machines hardware and since we can connect to the server if we have enough luck it is also not a problem with our ISP connection, anti-virus and/or firewall (otherwise we wern't be able to connect to our 1.7.10 server).

We have no problem with a compareable 1.7.10 modpack which has also 230+ but since we started 1.12.2 it is horrible to connect and every time the DC happened while this config sync so it must be a problem with this library and nothing else but since many mods depending on this lib we can't go an kick it out so a lockthrough/fix for this should be made which should be to compleatly disable the packet sync or make it possibly to disable it as it isn't needed because normaly all configs are identical and if I take a look in the config it isn't worth to send any kind of config sync packet compared with other mods.

Also when the server is started with this:

*INVOCATION="java -server -Xms${MINHEAP}G -Xmx${MAXHEAP}G -XX:MaxPermSize=${INITMEM}M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -d64 -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=$CPU_COUNT -XX:+AggressiveOpts -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -jar $SERVICE nogui"* - Then only one person can connect but if I change it like this:

*INVOCATION="java -server -Xms${MINHEAP}G -Xmx${MAXHEAP}G -XX:+UseG1GC -d64 -XX:SoftRefLRUPolicyMSPerMB=1 -XX:+UseAdaptiveGCBoundary -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -jar $SERVICE nogui"
* - One person can not connect but sometimes a few others and if I only use:

*INVOCATION="java -server -Xms${MINHEAP}G -Xmx${MAXHEAP}G -jar $SERVICE nogui"* - All have either luck with connecting or getting DC'ed while sending the config sync packet.

Screen of proof: https://i.imgur.com/l19e3BV.png

We don't know why this happend but it is anoying and definitly not fun to play with all those DCs.

**Comment by covers1624** [comment]
I can tell you that CCL is definitely not the cause of this. Unless you have an unreleased dev version of one of my mods, the config syncing system isn't used anywhere and is a recent addition, it would basically be sending a blank packet as far as this issue is concerned. There are many things that can cause this timeout, its usually related to a slow internet connection and someone sending a large packet on join. Just because the last thing in the console was me printing out that I'm sending a packet doesn't mean that my packet was the issue, who knows what packet was sent. There was a mod that increases the timeout, but i cannot remember what one, @gigabit101 should know. Anyway, i can guarente that CCL's config sync packet is not the cause for this.

**Comment by covers1624** [comment]
Addition, im going ahead and cleaning up the logging for the packet, to make it clearer what mod's configs are syncing and also adding a config to completely disable syncing.
