### ISSUE TITLE
A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.

### ISSUE THREAD

**Issue by darthvader45** [TheCBProject/CodeChickenLib#183]
I keep getting this error when creating or loading a world with codechickenlib installed.  The only other mod with error messages is Bibliocraft, and that mod had no conflicts with it before.  What could be causing the problems?

**Comment by covers1624** [comment]
Those can actually be ignored, is there any specific issue here? or are you just curious about the log line?

**Comment by darthvader45** [comment]
Okay nvm, stupid Chisel requiring the CTM mod.

**Comment by Akaruz64** [comment]
Hey, i'm having the same line on the log, when it happens, the game actually freezes and a lot of particles stop rendering. like the one when you break a block or botania mana pulses for ex, everything keeps working, it doesn't crash, but it gets annoying not seeing some things, do you have any clue at what may be causing this?

**Comment by darthvader45** [comment]
Can you show us the log?  Might help to point out where the error might be coming from.

**Comment by darthvader45** [comment]
If all else fails, the 50/50 strategy might help to find any possible conflicts.

**Comment by Akaruz64** [comment]
Hey, just found out thanks to the log of another mod which mod was that was causing me this issue, it is  Fire and Ice doing some Illegal Thread Access with one of the mobs particles it spawn.
Thanks for the response thou, CCL did show me the warning, then when i added Phosphor on a whim, it showed me the actual details that were causing this problem.

If this helps you or another with a similar cause, it may be the mod, the link to the issue is https://github.com/Alex-the-666/Ice_and_Fire/issues/1530

Regards!
