### ISSUE TITLE
LEAK: ByteBuf.release() was not called before it's garbage-collected

### ISSUE THREAD

**Issue by LemADEC** [TheCBProject/CodeChickenLib#220]
As of CodeChickenLib-1.12.2-3.2.2.353-universal.jar, a leak is detected periodically in our (large) modpack.
When activating advanced logs, we get this https://gist.github.com/LemADEC/ff3b7ed0d67c1f46390360d10c7ef587

When it's detected, leak is reported as the world is being saved.
It doesn't happen each time the world is saved. Exact trigger is unknown at this time.

Here's the list of mods that have explicit dependency with codechickenlib in our modpack are:
BrandonsCore-1.12.2-2.4.9.195 > Draconic-Evolution-1.12.2-2.3.18.329
EnderStorage-1.12.2-2.4.5.135
ForgeMultipart-1.12.2-2.6.0.79
MrTJPCore-1.12.2-2.1.3.35 > ProjectRed-1.12.2-4.9.1.92-*
DankNull-1.12-1.4.43
ThermalExpansion-1.12.2-5.5.2.39
ThermalDynamics-1.12.2-2.5.3.16

**Comment by FiveEYZ** [comment]
Been seeing this for a long time now, after I enabled the advanced flag I got exactly the same report: https://gist.github.com/FiveEYZ/e94510b948ebdd51d85162a61155dc23/
full log: https://gist.github.com/FiveEYZ/6d1d608f55c534a9eebdb777518d227a

Never seen this being triggered on a empty server, only a few minutes AFTER first player joins the server after each restart.

Using: FTB Revelation 2.7.0 with forge-1.12.2-14.23.5.2808-universal

**Comment by NLBlacky** [comment]
This leak is still happening on alot of modpacks since most modpacks have either draconic evolution, enderstorage, thermal or danknull in the modpack. When can we expect an update on this? It was labeled as a bug 4,5 months ago and the last mod update was 10 months ago. 

Our java leak report: https://gist.github.com/NLBlacky/62728b0abcf37ffe0ae2062d0d591eb8

**Comment by Phantum** [comment]
https://gist.github.com/Phantum/834a8892e6b7ef4d28e8dfa08338a52a

Getting this as well, Have alerted Railcraft about this also.

**Comment by binary404** [comment]
i also have been having this issue it. i have also been having client memory leak problems but i am not sure if it is caused by code chicken lib or not

**Comment by binary404** [comment]
codechicken.lib.packet.PacketCustom.<init>(PacketCustom.java:216)      codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:84)      codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:69) 
the problem seems to be caused by packets

**Comment by covers1624** [comment]
I've added a release call to ByteBuf in there, but sadly i don't think ill be able to fix the root problem without a serious rework of the system.
