### ISSUE TITLE
CodeChickenLib causes Lava Vision to fail

### ISSUE THREAD

**Issue by Dr-WeiAL** [TheCBProject/CodeChickenLib#382]
Alex-the-666/AlexsMobs#722
I don’t know what the situation is, but he said he needs your solution

**Comment by covers1624** [comment]
I am very disappointed with the blatant disregard for investigating the issue and blame moving happening with this issue.

This does appear to be a cross mod compact issue, ultimately stemming from AlexsMobs and can properly be solved their side.

CCL wraps the [`BlockRendererDispatcher`](https://github.com/TheCBProject/CodeChickenLib/blob/master/src/main/java/codechicken/lib/render/block/CCBlockRendererDispatcher.java) to intercept calls for various purposes, this is nothing new, it has done this since 1.12.2.

It does this properly, by fully wrapping the previous `BlockRendererDispatcher` and forwarding all calls through to the wrapped instance.

AlexsMobs just replaces the `liquidBlockRenderer` field, which, when CCL is installed, literally does nothing as the wrapped `BlockRendererDispatcher` does not use this field. CCL cannot simply set the wrapped `BlockRenderDispatcher`s `liquidBlockRenderer` field on each call, as the parent could have chosen to do something custom (i.e another mod wrapping the BRD).

The proper solution here is to fully wrap and forward all calls the `BlockRendererDispatcher` does the exact same way CCL does this, and instead of replacing the `liquidBlockRenderer` intercepting the call to `renderLiquid` and doing something custom there.

Alternatively, Mixins exist. Copy and pasting large chunks of Vanilla code the way AlexsMobs is doing might be considered a Eula violation and should be avoided.

This will not and cannot be resolved CCL's side.
