### ISSUE TITLE
Batching Chunks 1.11.2 

### ISSUE THREAD

**Issue by captcookie** [TheCBProject/CodeChickenLib#59]
https://pastebin.com/NnthnPAp

1.11.2 Multiplayer server
Anyone that gets near the chunk crashes to the launcher.

**Comment by OrdinatorStouff** [comment]
Not the exact same stacktrace but I think this is related (codechicken.lib.render.block.CCBlockRendererDispatcher). We have the same thing in 1.11.2 client crashes when near the offending chunk: https://pastebin.com/baxVnkBq

CodeChickenLib-1.11.2-2.7.0.268-universal.jar

**Comment by covers1624** [comment]
Someones block is failing to render, then crashing whilst attempting to build the proper crash report, Im unable to fix this and this is not a CCL issue, I simply wrap vanilla's render dispatcher and forward to vanilla if it isnt something i need to handle.

**Comment by kreezxil** [comment]
This error you don't want to fix that is only being caused by this mod has crept up again in 1.12.

https://pastebin.com/bV3RS4R2 using codechicken lib 1.8.+ 1.12-3.1.1.288

Since you are unable to fix it, my only recourse is to remove the mod and all the other mods that depend on it. I was looking for a way to remove some fat from Colonial Expansion, this is not how I wanted to do it.

Please reconsider how you render things, maybe there is something you can do to alleviate the issue. Maybe some kind of try|catch around the wrapper to the vanilla renderer to capture the npe and allow things to continue unabated.

**Comment by OrdinatorStouff** [comment]
@kreezxil I have handled a couple "batching chunks" errors on our ATM3 server (1.12). As covers already said a while back the problem isn't *caused* by CCL, it's that CCL is the one showing up in the report. Your hostile and combative response makes me think you're not interested in trying to actually troubleshoot but if I'm wrong, here's some tips:

For us, the problem was Pam's Harvestcraft blocks (i.e. the market). I was able to figure that out because the full client log (fml-client-latest.log or in my case fml-junk-earlystartup.log) printed a stacktrace/crash just before the CCL batching chunks got caught up in it and clearly identified Pam's and even the exact block that was causing the trouble. I edited the save/region files with NBTExplorer and deleted any pam's markets in the region and the crashes had stopped completely. For you it might not be Pam's, and possibly might not be able to find more details in the other logs, but there's a good chance that you can and find out what's *actually* causing trouble instead of CCL

**Comment by covers1624** [comment]
Yeah, this is entirely out of my hands, the most i can do is try catch the call to vanilla's renderer and spam the console with as much info as i can, anyone able to provide a world download / mods list?

**Comment by kreezxil** [comment]
Spam the console might be good. I do have Pam's Harvestcraft in the pack.

@ATM3 I'd call it frustration.

On Aug 21, 2017 2:01 AM, "covers1624" <notifications@github.com> wrote:

Yeah, this is entirely out of my hands, the most i can do is try catch the
call to vanilla's renderer and spam the console with as much info as i can,
anyone able to provide a world download / mods list?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TheCBProject/CodeChickenLib/issues/59#issuecomment-323662524>,
or mute the thread
