### ISSUE TITLE
[1.11.2] Chunk Generation Crash

### ISSUE THREAD

**Issue by hugeblank** [TheCBProject/CodeChickenLib#99]
[Here](https://pastebin.com/u26xrqiE)'s the crash log.

What happened:
A player on my server loaded a dimension and while it loaded in, they crashed. It looks like it has something to do with CodeChickenLib, but I'm not totally sure.

**Comment by covers1624** [comment]
Update your mods, this is ccl being blamed for another mods crash, I've pushed updates to catch this issue and yell at the console, ultimately the issue was tracked down to pams and I'm not sure if a 1.11 fix has been pushed but I did push a pr for 1.12. This is a duplicate, look at the other closed issues, on mobile can't really link an issue.
